// error messages
const TAX_ID_EXISTS = "TAX_ID_EXISTS";
const INVALID_TAX_ID = "INVALID_TAX_ID";
const INVALID_ID = "INVALID_ID";
const COMPANY_NOT_FOUND = "COMPANY_NOT_FOUND";
const INVALID_COMPANY_DATA = "INVALID_COMPANY_DATA";
const COMPANY_DELETED = "COMPANY_DELETED";
const COMPANY_CREATED = "COMPANY_CREATED";
const COMPANY_UPDATED = "COMPANY_UPDATED";

export const ERROR_CODES = Object.freeze({
  TAX_ID_EXISTS,
  INVALID_TAX_ID,
  INVALID_ID,
  COMPANY_NOT_FOUND,
  INVALID_COMPANY_DATA,
  COMPANY_DELETED,
  COMPANY_CREATED,
  COMPANY_UPDATED,
});
